### Purpose: Load the wine datasets (Red, White, Sparkinling, Rose) and clean the data so it can be loaded into SQL

In [1]:
# Import dependencies
import pandas as pd
import os
import re

In [2]:
# Load in the red wine data
red_data = os.path.join("Resources","Red.csv")
red_df = pd.read_csv(red_data)

red_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016

In [3]:
# Add a column for wine type
red_df["Variety"] = 'Red'
red_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,Variety
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,Red
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,Red
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,Red
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,Red
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,Red

In [4]:
# Load in the white wine data
white_data = os.path.join("Resources","White.csv")
white_df = pd.read_csv(red_data)

white_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016

In [5]:
# Add a column for wine type
white_df["Variety"] = 'White'
white_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,Variety
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,White
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,White
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,White
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,White
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,White

In [6]:
# Load in the rose data
rose_data = os.path.join("Resources","Rose.csv")
rose_df = pd.read_csv(rose_data)

rose_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Mad Méditerranée Rosé 2019,France,Méditerranée,Château Camparnaud,4.0,25,10.11,2019
1,Redoma Rosé 2019,Portugal,Douro,Niepoort,3.9,25,12.81,2019
2,Fantini Cerasuolo d'Abruzzo 2019,Italy,Abruzzo,Farnese,3.6,25,5.60,2019
3,Mount Hermon Rosé 2017,Israel,Galilee,Hermon,3.4,25,12.14,2017
4,La Villa Rosé 2018,France,Languedoc,Château La Sauvageonne,4.6,25,68.95,2018

In [7]:
# Add a column for wine type
rose_df["Variety"] = 'Rose'
rose_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,Variety
0,Mad Méditerranée Rosé 2019,France,Méditerranée,Château Camparnaud,4.0,25,10.11,2019,Rose
1,Redoma Rosé 2019,Portugal,Douro,Niepoort,3.9,25,12.81,2019,Rose
2,Fantini Cerasuolo d'Abruzzo 2019,Italy,Abruzzo,Farnese,3.6,25,5.60,2019,Rose
3,Mount Hermon Rosé 2017,Israel,Galilee,Hermon,3.4,25,12.14,2017,Rose
4,La Villa Rosé 2018,France,Languedoc,Château La Sauvageonne,4.6,25,68.95,2018,Rose

In [8]:
# Load in the rose data
sparkling_data = os.path.join("Resources","Sparkling.csv")
sparkling_df = pd.read_csv(sparkling_data)

sparkling_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Crémant de Loire Brut 2017,France,Crémant de Loire,Langlois-Chateau,3.9,25,14.41,2017
1,Vicar's Choice Sauvignon Blanc Bubbles 2019,New Zealand,Marlborough,Saint Clair,4.2,25,11.90,2019
2,Crémant de Limoux Brut N.V.,France,Crémant de Limoux,Prima Perla,3.5,25,14.32,N.V.
3,Athesis Brut 2016,Italy,Südtirol - Alto Adige,Kettmeir,4.0,25,21.50,2016
4,Blanc de Blancs Réserve Brut Nature N.V.,Germany,Pfalz,Eymann,3.9,25,31.18,N.V.

In [9]:
# Add a column for wine type
sparkling_df["Variety"] = 'Sparkling'
sparkling_df.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,Variety
0,Crémant de Loire Brut 2017,France,Crémant de Loire,Langlois-Chateau,3.9,25,14.41,2017,Sparkling
1,Vicar's Choice Sauvignon Blanc Bubbles 2019,New Zealand,Marlborough,Saint Clair,4.2,25,11.90,2019,Sparkling
2,Crémant de Limoux Brut N.V.,France,Crémant de Limoux,Prima Perla,3.5,25,14.32,N.V.,Sparkling
3,Athesis Brut 2016,Italy,Südtirol - Alto Adige,Kettmeir,4.0,25,21.50,2016,Sparkling
4,Blanc de Blancs Réserve Brut Nature N.V.,Germany,Pfalz,Eymann,3.9,25,31.18,N.V.,Sparkling

In [10]:
compiled_df = pd.concat([red_df, white_df, rose_df, sparkling_df], axis=0)
compiled_df

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,Variety
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,Red
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,Red
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,Red
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,Red
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,Red
...,...,...,...,...,...,...,...,...,...
1002,Special Cuvée Brut Aÿ Champagne N.V.,France,Champagne,Bollinger,4.2,37765,46.00,N.V.,Sparkling
1003,Brut Premier Champagne N.V.,France,Champagne Premier Cru,Louis Roederer,4.2,40004,36.48,N.V.,Sparkling
1004,Impérial Brut Champagne N.V.,France,Champagne,Moët & Chandon,4.1,76037,40.61,N.V.,Sparkling
1005,Brut (Carte Jaune) Champagne N.V.,France,Champagne,Veuve Clicquot,4.2,86839,43.60,N.V.,Sparkling
1006,Brut Champagne N.V.,France,Champagne,Dom Pérignon,4.6,94287,170.00,N.V.,Sparkling

In [11]:
# Export the compiled dataframe to a csv
compiled_df.to_csv('Resources/compiled_wine.csv', index=False)